---
bibliography: references.bib
format:
  pdf:
    keep-tex: true
    number-sections: true
    include-in-header: latex-header.tex
execute:
  warning: false
editor: source
---

**Manuscript type:** Article

**Title:** Quantifying how biodiversity affects ecosystem functioning across space and time in natural marine ecosystems

**Authors:** James G. Hagan$^{1, 2, 3}$\*, Benedikt Schrofner-Brunner$^{2, 3}$ and Lars Gamfeldt$^{2, 3, 4}$

1.  Community Ecology Lab, Department of Biology, Vrije Universiteit Brussel (VUB), Pleinlaan 2, 1050 Brussels, Belgium\
2.  Department of Marine Sciences, University of Gothenburg, Box 461, SE-40530, Gothenburg, Sweden\
3.  Gothenburg Global Biodiversity Centre, Box 461, SE-40530, Gothenburg, Sweden\
4.  Centre for Sea and Society, Box 260, SE-40530, Gothenburg, Sweden

**Corresponding author:** James G. Hagan (james_hagan\@outlook.com)

**Data availability:** Raw data for case study 1 are available on Github (https://github.com/haganjam/BEF_quant_scale) and will be archived upon publication. Raw data for case study 2 are archived on ResearchBox and will be public upon publication: (https://researchbox.org/843&PEER_REVIEW_passcode=GLGJFF).

**Code availability:** All code used to perform the analysis can be found on Github: (https://github.com/haganjam/BEF_quant_scale) and will be archived on Zenodo upon publication.

**Key words:** biodiversity, ecosystem function, scale, semi-natural ecosystem, statistical partition

## Abstract

Most empirical work investigating the importance of biodiversity for ecosystem functioning has taken place on small spatial and temporal scales. Therefore, we need to improve our understanding at larger spatial and temporal scales if we want biodiversity-ecosystem functioning science to be relevant for policy and management. We built a methodological pipeline around a rigorously derived statistical partition that allowed us to distinguish the various ways in which biodiversity can affect functioning in two natural marine ecosystems (intertidal rockpool macroalgae and marine fouling communities). This partitioning considers both local species interactions and species' asynchronous responses to varying environments over space and time. We found that a combination of local-scale species interactions, local-scale dominance by high functioning species, and spatial niche partitioning contributed to a positive effect of biodiversity on ecosystem functioning in these ecosystems. Moreover, the importance of spatial niche partitioning tended to strengthen with increasing spatial environmental heterogeneity. Our approach allowed us to directly quantify the complex ways in which biodiversity can affect ecosystem functioning and highlights the importance of taking a multi-scale perspective in biodiversity-ecosystem functioning research.

## Introduction

Concerns over declines in biodiversity in the 1990s prompted ecologists to study how biodiversity loss may affect the functioning of ecosystems [@delaplante2011; @frank2022]. Since then, substantial experimental work has shown that biodiversity is important for sustaining ecosystem functioning [@cardinale2012; @tilman2014]. The bulk of these experiments have been performed at small spatial scales, and researchers have intentionally worked under relatively homogeneous environmental conditions [@qiu2020; @gonzalez2020; @gamfeldt2023; @hagan2024]. However, environmental heterogeneity, both in space and time, is an important mediator of species coexistence [@hart2017], and biodiversity is often changing at multiple scales [@mcgill2015]. Thus, there is a need to improve our understanding of the biodiversity-ecosystem functioning relationship at large spatial and temporal scales in natural ecosystems [@gonzalez2020; @isbell2017]. This is especially important if we want biodiversity-functioning science to be relevant for policy and management [@isbell2017; @leprovost2023].

At local scales, changes in biodiversity are unambiguously considered to affect functioning if mixtures of species have higher (or lower) functioning than expected [@petchey2003]. This expectation is based on each species' functioning in monoculture (i.e. without local species interactions), and the expected functioning of each species in mixture (referred to as expected relative yield, $RYE$). The deviation of a mixture from this null expectation is called a net biodiversity effect and quantifies the magnitude of the effect of biodiversity on ecosystem function [@loreau2001]. Using a classic statistical partition [@loreau2001], it was shown that there are at least two sets of mechanisms that can lead to net biodiversity effects (but see @fox2005). The first is referred to as complementarity. Positive complementarity occurs when there is niche partitioning or positive interactions among co-occurring species outweigh any negative interactions [@cardinale2011; @williams2017]. The second is called selection, which is positive when species with high levels of ecosystem function in monoculture dominate functioning in species mixtures [@creed2009; @spaak2021]. Understanding complementarity and selection is important because their relative strength determines how we interpret the way biodiversity affects functioning. Specifically, complementarity is maximised when species coexist and/or interact positively. This implies that many species are required to maintain high levels of ecosystem functioning at a local scale. In contrast, selection is maximised when one or a few high functioning species dominate functioning, which implies that only one or a few species are required to maintain high levels of ecosystem functioning.

Experimental work at local scales has shown that complementarity and selection are frequently of similar magnitude [@cardinale2007; @cardinale2011] (but see [@hong2022]). Moreover, in experiments, the highest functioning species in monoculture often has higher functioning than the most diverse mixture of species [@gamfeldt2023; @cardinale2011; @gamfeldt2015], and in many natural systems, a few dominant species tend to explain ecosystem functioning [@smith2003; @smith2020; @lisner2023]. Even though local functioning might be largely controlled by a few dominant species, this does not mean that biodiversity is not important. Rather, if the identity of the dominant species varies across space and time, biodiversity may still be important at larger scales. This idea has been formalised as the insurance hypothesis for the effect of biodiversity on ecosystem functioning (reviewed in [@loreau2021]). The insurance hypothesis states that, when species respond asynchronously to environmental variation in space and time and dominate places and times where/when they are highest functioning in monoculture, biodiversity increases both the magnitude and stability of ecosystem functioning at larger scales [@yachi1999; @loreau2003]. For example, a temporal insurance effect occurs when species respond asynchronously to temporal environmental variation and dominate during the times when they are highest functioning [@yachi1999].

Attempts to quantify the effects of biodiversity on ecosystem functioning at large scales have generally focused on examining whether the slope of the relationship between biodiversity and ecosystem functioning changes with increasing spatial/temporal extents or grains (where extent and grain are defined *sensu* @chase2013). Theoretical models investigating this have typically found that the slope can indeed change with increasing grain [@thompson2018; @thompson2021] and extent [@barry2021]. Empirical studies that correlated biodiversity with measures of ecosystem functioning at different spatial extents and grains in natural systems [@craven2020; @chisholm2013] reached similar conclusions. One issue with these studies is that the change in the slope of the relationship between biodiversity and functioning is sensitive to details such as whether functioning is averaged or summed within a given spatial unit [@barry2021], or how spatial units are aggregated to increase scale (compare [@thompson2018; @thompson2021]). The focus on the slope means that neither net biodiversity effects nor insurance effects have been directly calculated or compared across spatial and temporal scales in natural ecosystems.

Fig. 1: Overview of the additive statistical partition of biodiversity effects across spatial and temporal scales. (a) How the net biodiversity effect (NBE) is calculated and additively partitioned into total complementarity (TC) and total selection (TS). Total selection is then further partitioned into five terms that describe how biodiversity can affect function across times and places: average selection (AS), temporal insurance (TI), spatial insurance (SI), spatio-temporal insurance (ST) and a residual term called non-random overyielding (NO). Total insurance (IT) is the sum of AS, IT, SI and ST (see Table 1 for abbreviations). (b) Hypothetical examples with two species, two times and two places to give an intuition of what these biodiversity effects measure. For example, total complementarity quantifies the part of the net biodiversity effect that is due to local-scale interactions among species whilst spatial insurance quantifies the extent to which species that are high functioning in monoculture at a particular place tend to dominate the mixtures in those places (see SI Appendix 1, Table S1 for ecological explanations of the different terms).

| Symbol                                         | Explanation                                                                           |
|----------------------------|--------------------------------------------|
| ( P, T, S )                                    | Number of places ((k)), times ((j)), and species ((i)) respectively                   |
| ( M\_{ijk} )                                   | Monoculture function of species (i), at place (k) and time (j)                        |
| ( Y\_{ijk} )                                   | Observed function of species (i), at place (k) and time (j) in mixture                |
| ( RY\_{Fijk} )                                 | Expected initial proportion of species (i) at place (k), and time (j) in mixture      |
| ( RY\_{Oijk} = Y\_{ijk} / M\_{ijk} )           | Observed relative yield of species (i) at place (k) and time (j) in mixture           |
| ( \Delta RY\_{ijk} = RY\_{Oijk} - RY\_{Fijk} ) | Change in relative yield of species (i) at place (k) and time (j) in mixture          |
| ( p\_{Oijk} )                                  | Observed relative functioning of species (i), at place (k) and time (j) in mixture    |
| ( \Delta RY\_{Oijk} = RY\_{Oijk} - p\_{Oijk} ) | Change in observed relative yield of species (i) at place (k) and time (j) in mixture |
| ( \Delta p\_{ijk} = p\_{Oijk} - RY\_{Fijk} )   | Change in relative functioning of species (i) at place (k) and time (j) in mixture    |

: Guide to the symbols used in the equations of the statistical partition. Symbols correspond to those used in Fig. 1, the Method and materials section, and SI Appendix 2. {#tbl-table-1}

Recently, an extension of original complementarity-selection statistical partition [@loreau2001] was developed [@isbell2018]. The extension quantifies a net biodiversity effect in different places and times and partitions it into a set of effects that describe how biodiversity can affect functioning at local and larger scales of space and time (see Fig. 1 for an overview, and SI Appendix 2 for details). Specifically, total complementarity quantifies the average effect of local-scale interactions among coexisting (or co-occurring) species on functioning. For example, if total complementarity is positive then, on average, interactions between individuals of different species reduce functioning less than interactions between individuals of the same species (Fig. 1b). Total selection is divided into non-random overyielding and total insurance. Non-random overyielding is a residual term describing the tendency for species that are high functioning in monoculture to overyield most and is usually negative (Fig. 1b and SI Appendix 1, Table S1 for details). Total insurance, when positive, quantifies the extent to which species that are high functioning in monoculture tend to dominate mixtures. Dominance of species in mixtures that are high functioning in monoculture occurs in four ways [@isbell2018]: average selection, spatial insurance, temporal insurance and spatio-temporal insurance (Fig. 1a). For example, average selection quantifies part of the net biodiversity effect that is due to a single high functioning species in monoculture dominating across all places and times (Fig. 1b), whilst spatial insurance quantifies the part of the net biodiversity effect that is due to different species dominating mixtures in different places where they are also high functioning in monoculture (Fig. 1b). Quantifying these effects allows the estimation and comparison of biodiversity effects on ecosystem functioning through local-scale interactions, dominance by high functioning species along with spatial and temporal niche partitioning at large scales. As a result, this statistical partition has clear advantages over approaches that examine the slope of the relationship between biodiversity and functioning.

Despite its potential, this approach has only been applied in the original paper on data from a controlled grassland biodiversity experiment [@isbell2018; @reich2001] and, more recently, in a spatial context [@castillioni2023]. Here, we fill this gap by directly quantifying the magnitude of the effect of biodiversity on ecosystem functioning at large spatial and temporal scales in two natural marine ecosystems: intertidal rockpool macroalgae (*case study 1*), and marine fouling communities (*case study 2*). For the rockpool macroalgae, we created monocultures of four species of canopy-forming brown macroalgae and a mixture of all four species, which we sampled three times over a six-month period at two rocky shores (i.e. two places) (see Fig. 2a and *Methods and materials*). The marine fouling study included monocultures and mixtures of five marine sessile operational taxonomic units, from nine different clusters consisting of three to five places each (39 places in total). We sampled the fouling communities three times over six weeks (see Fig. 2b and *Methods and materials*). In contrast to experiments in controlled environments, data from natural systems often have incomplete data on species in monoculture and their expected relative yields ($RYEs$). Our rockpool study had complete data for monocultures but lacked information on $RYE$s, whereas the fouling data had both incomplete monoculture data and no information on $RYE$s. Therefore, we developed a methodological pipeline that combines data imputation techniques for dealing with incomplete monoculture data along with uncertainty assumptions for the RYEs (Methods and materials and SI Appendix 3). Using this pipeline and applying the partition to two marine ecosystems allowed us to determine both the magnitude of the net biodiversity effect and how much of it is due to local-scale interactions compared to insurance effects operating at larger scales. We show that insurance effects of biodiversity can be large and positive and tend to increase when we consider larger spatial scales where spatial environmental heterogeneity is higher. In doing so, we provide insights into how biodiversity at different spatial and temporal scales contributes to ecosystem functioning.

Fig. 2: Data structure of the marine ecosystems for which we quantified the biodiversity effects. (a) The rockpool macroalgae dataset (case study 1) consists of two shores (KS -- Kingsand, CB -- Challaborough) near Plymouth, United Kingdom, for which the percentage cover of monocultures (M) of four species (Bifurcaria bifurcata, Fucus serratus, Laminaria digitata and Sargassum muticum) and a mixture (Y) of the four species were measured three times (t1-3). (b) The marine fouling communities (case study 2) consist of nine clusters (cluster F was excluded due to loss of replicates) of between three and five sites in the Tjärnö archipelago on the Swedish west coast (39 places in total). We measured the dry biomass of mixtures at each of the 39 places on three times (t1-3). We also gathered 287 direct measurements of monoculture dry biomass for the five operational taxonomic units across places and times. We used these monoculture measurements to impute the remaining 298 required monoculture dry biomass measurements (Methods and materials).

## Materials and methods

### Overview of the methodological pipeline

The statistical partition we used to calculate the different biodiversity effects (Fig. 1 and SI Appendix 2) was originally developed for experimental data [@isbell2018]. This is because the partition requires extensive monoculture (i.e. monoculture data for all species in all places and at all times for which mixture data are available), which can relatively easily be generated by inoculating species into habitat patches in monoculture [@cardinale2011; @reich2001]. In addition, seven of the nine biodiversity effects (net biodiversity effect, total selection, total insurance, average selection, spatial insurance, temporal insurance and spatio-temporal insurance) require knowing species' expected relative yields ($RYE$s) for all species in all places and at all times (see SI Appendix 3 for an explanation as to why total complementarity and non-random overyielding can be calculated without RYEs). In most biodiversity-ecosystem functioning experiments, mixtures of species are inoculated with equal initial relative abundance. For example, in a two-species mixture at a given place and time, both species would be initially inoculated with 0.5 relative abundance. These initial relative abundances are then used as the $RYE$s [@loreau2001].

The problem with data from natural systems is that we usually do not have monoculture data for all species in all places and at all times. Rather, we might have patchy, natural monoculture data [@gamfeldt2013; @jochum2020] or we might be able to collect some monoculture data through, for example, species removals [@sears2007]. Moreover, we do not have $RYE$s because we do not know the colonisation history that occurred in a given place over time. To apply the statistical partition and calculate the different biodiversity effects on field data from natural systems requires a methodological pipeline that can solve these issues.

Here, we propose such a pipeline. First, to deal with the problem of incomplete monoculture data, we use data imputation techniques. If we are able to gather enough known monoculture (i.e. naturally occurring monocultures or artificially created monocultures), we can then use statistical data imputation methods to obtain a distribution of estimates for the required missing monoculture data. Obtaining a distribution of estimates for each missing monoculture is especially suited to a Bayesian framework which is what we use (see SI Appendix 4.6 for a detailed description of our method of monoculture imputation, which we applied in our case study on marine fouling communities).

Second, to deal with not knowing the $RYE$s, we assume that all species are initially present at all times and in all places but that the exact $RYE$s of each species are unknown. We then assume a set of random $RYE$s that we draw from a Dirichlet distribution (a probability distribution that outputs a simplex) and calculate the different biodiversity effects. We repeat these calculations 100 times with different sets of $RYE$s. This provides a distribution of possible biodiversity effects, which includes the uncertainty from not knowing the true $RYE$s in each place and at each time (SI Appendix 3). On simulated data, the Pearson correlation coefficient between the true, simulated biodiversity effect and the mean of the distribution of biodiversity effects obtained by assuming random sets of $RYE$s exceeded 0.94 for the seven biodiversity effects that are sensitive to $RYE$s (SI Appendix 3, Fig. S11). Moreover, the 95% percentile interval of each estimated biodiversity effect (obtained from calculating these effects 100 times assuming different RYEs) contained the true, simulated biodiversity effect in more than 80% of the simulations for all biodiversity effects except average selection and spatial insurance (SI Appendix 3, Table S6). But even in those cases, the bias was relatively small in comparison to the average size of the effect (see SI Appendix 3 for further analyses). Thus, on simulated data, this procedure provides a reliable way to quantify the biodiversity effects when $RYE$s are unknown.

### Case study 1: Rockpool macroalgae

We used our methodological pipeline to apply the statistical partition of biodiversity effects to data from two natural marine ecosystems. The first is a case study based on a removal experiment where communities of four macroalgal species (*Bifurcaria bifurcata* Ross, *Fucus serratus* Linnaeus, *Laminaria digitata* (Hudson) Lamouroux, and *Sargassum muticum* (Yendo Fensholt) were manipulated in marine rockpools near Plymouth, United Kingdom. The four species were chosen because they are conspicuous members of the local intertidal flora and can dominate the cover in tide pools (Lars Gamfeldt, personal observation). The removal was done on two different shores (Challaborough, 50° 17' N, 3° 54' W and Kingsand, 50° 20' N, 4° 11' W) that were relatively environmentally similar (Lars Gamfeldt, personal observation). In June 2007, the rock pools were manually cleared of all visible animal and algae biomass. All pools were at the mid-height of the shores and ranged in size from approximately 0.2 to 1 m in diameter and 0.1 to 0.4 m in depth. We manipulated the presence and absence of the four focal species by continuously (monthly throughout the duration of the experiment) scraping off the holdfasts of all small germlings of the target species. By preventing the establishment of new recruits, we created two treatments: **(i)** monocultures of each focal algal species and **(ii)** a mixture of the four focal species. There were between three and four replicate rockpools each monoculture, and between six and seven rockpools for the mixture. Treatments were randomly assigned to rockpools. The percentage cover of algae in the rockpools as a proxy for biomass was estimated three times: March, July and September 2008. Algal cover typically correlates strongly with biomass [@stachowicz1999; @bracken2017] but see [@masterson2008] for counterexamples. At each site and at each time, we averaged the total percentage cover across the replicates for the mixture and the monoculture rockpools. Thus, we have mixture and monoculture data for two places and three times (Fig. 2a).

Given that we had complete monoculture data for this case study, we simply calculated the different biodiversity effects assuming a set of 100 random $RYE$s drawn from the Dirichlet distribution, which left us with a distribution of 100 biodiversity effects for the net biodiversity effect, total selection, total insurance, average selection, spatial insurance, temporal insurance and spatio-temporal insurance (total complementarity and non-random overyielding are unaffected by RYEs, SI Appendix 3). We parameterised the Dirichlet distribution with four $\alpha$-values equal to three. Exploratory simulations showed that $\alpha$-values equal to three provide a good spread of possible $RYE$s (SI Appendix 3, Fig. S7). We also examined the relationship between monoculture percentage cover and relative abundances across times and places. Because the two different shores were environmentally similar and the time between measurements was only between five and six months, we did not expect strong insurance effects of biodiversity in this dataset.

### Case study 2: Marine fouling communities

The second case study includes data on communities consisting of up to five species of marine fouling organisms on settling plates. We created mixtures and monocultures with locally occurring marine fouling organisms between the 7th of July 2022 and the 5th of September 2022 (60 days) in the archipelago around Tjärnö (58° 52' 30.0 " N 11° 08' 42.0 " E) on the Swedish west coast (SI Appendix 4, Fig. S12b). For this, we installed 600 PMMA panels (10 x 11 cm, transparent with a removable black background) at 50 sites in the archipelago. Each site consisted of 12 panels mounted on a frame hanging from a buoy at 3 m or 6 m depth (SI Appendix 4, Fig. S12). Of the 12 panels, three were randomly assigned as mixture panels and nine were assigned as monoculture panels. The three mixture panels correspond to three temporal replicates that we sampled destructively at three different times. The 50 sites were grouped into 10 clusters to represent different seascapes (SI Appendix 4, Fig. S12a). We made sure that there was at least 40 m between sites within a cluster.

When choosing the sites, we aimed to create five environmentally heterogeneous and five environmentally homogeneous clusters. We did this using *a priori* geographical data (see SI Appendix 4.2). After the experiment, we then directly quantified the level of spatial environmental heterogeneity in each cluster by calculating multivariate dispersion on 14 z-score standardised environmental variables: turbidity (depth of visibility (m), 15 m resolution), relative wave exposure (unitless, 15 m resolution) from geographic data [@greeve2025] along with variables that we measured *in situ* during the experiment, namely: distance from panel to the seabed (m), panel depth (m), the average, coefficient of variation, maximum and minimum temperature over the course of the experiment (ºC) and the average, coefficient of variation and maximum light level over the course of the experiment (lux), salinity (ppt), Secchi depth (m) and water movement (mass reduction g hour-1) (see SI Appendix 4.3 for details). Multivariate dispersion was calculated using the betadisper() function from the vegan package [@vegan] in R v4.1.2. We then compared multivariate dispersion between clusters originally designated as heterogeneous and homogeneous using Welch's two-sample t-test implemented using the t.test() function in R v4.1.2. We visualised the variation in environmental heterogeneity between clusters using a Principal Components Analysis (PCA) based on the same 14 z-score standardised environmental variables which we implemented using the prcomp() function in R v4.1.2. This analysis showed that there were considerable differences in spatial environmental heterogeneity between clusters (SI Appendix 1, Fig. S4).

For the mixture panels, organisms were allowed to settle and were left un-manipulated until sampled. For the monoculture panels, we waited until an organism had settled and was large enough to be identified and then removed all other species. This provided patchy monoculture data for different species at different times and different places. The organisms were identified to their lowest possible taxonomic resolution. Based on these identifications, we designated five operational taxonomic units (OTUs): Barn -- the barnacle, *Amphibalanus improvisus*, Bryo -- three bryozoa species (*Electra pilosa*, *Membranipora membranacea*, *Callopora rylandi*), Asci -- the solitary ascidian, *Ascidiella scabra*, Hydro -- two hydrozoan species (*Clytia* sp. and *Laomedea flexuosa*), and Ciona -- the solitary ascidian *Ciona intestinalis*. We hereafter refer to these taxonomic units as OTUs (reference pictures for the OTUs are available: https://researchbox.org/843&PEER_REVIEW_passcode=GLGJFF).

Monocultures were maintained on days 21, 32 and 42 during the experiment, and all panels were photographed before manipulation took place (Camera: Sony a6400 with Sony FE 2.8 / 50mm Macro and a polarisation filter). We retrieved mixtures and monocultures at three different time points (day 34, day 47 and day 60) for measurement in the lab. To avoid edge effects and disturbances from attachment holes39, we removed the panels' outer margin (1 cm). We photographed each panel on a light table (daylight Wafer 3), scraped off the organisms, and weighed them to 0.001 g accuracy (scale: Sartorius BP 110). For mixtures, the different OTUs were weighed separately. Then, samples were dried at 65 °C in a drying oven for 48 hours and weighed again to obtain dry biomass. Monoculture cover was determined using imageJ2 [@rueden2017]. We divided monoculture dry biomass by monoculture cover and multiplied by the total area of the panel to make the biomass measurements comparable to the unmanipulated mixtures (SI Appendix 4.4). We made sure that the panels representing different temporal replicates had similar species composition by correlating OTU cover values across time-points (SI Appendix 4.5).

During the experiment we lost 11 sites (including cluster F which we removed because only two sites were present at the end of the study) leaving us with 39 sites out of the original 50. This left us with data for 39 mixtures sampled at three time points (117 datapoints) and 287 monoculture datapoints. A complete mixture-monoculture dataset for this experiment would consist of monocultures of all five OTUs for the 39 mixtures at all three time points (i.e. 39 sites × 3 time points × 5 OTUs = 585 monoculture datapoints). We imputed the 298 missing monoculture dry biomass values using multilevel generalised linear models (GLM) fit in a Bayesian framework. To do this, we fit seven multilevel GLMs with the observed monoculture biomass (M) as the response variables and different combinations of each OTU's biomass in mixture (Y) along with environmental variation quantified using two principal components (PC1 and PC2). These two principal components were based on a PCA of nine environmental variables that were available at all places and times for the mixtures and monocultures, namely: distance from panel to the seabed (m), panel depth (m), the average, coefficient of variation, maximum and minimum temperature over the course of the experiment (ºC) and the average, coefficient of variation and maximum light level over the course of the experiment (lux). Together, PC1 and PC2 explained 74% of the variation in the nine environmental variables (SI Appendix 1, Fig. S5). To account for the positive continuous distribution of observed monoculture biomass values combined with the presence of true zeros (i.e. place-time combinations where a species had zero monoculture biomass), we used a Log-Normal hurdle model. A Log-Normal hurdle model is a mixture model where the response variable is modelled as zero or non-zero (0-1) using a Bernoulli process (i.e. logistic regression). Then, if the response variable is non-zero, it is modelled using a Log-Normal distribution. We present all seven models along with an intercept-only null model with priors in the supplementary information (SI Appendix 4.6). The posterior distributions of the seven models were estimated using Stan's No-U-Turn Sampler Hamiltonian Monte Carlo algorithm (https://mc-stan.org) with four separate chains. We implemented this in R v4.1.2 using the rstan package [@rstan]. We assessed model convergence by inspecting trace plots, the Gelman-Rubin statistic (R-hat values) and effective samples sizes.

The seven models were ranked using the leave-one-out cross validation score which we estimated using Pareto Smoothed Importance Sampling (PSIS) implemented using the loo() function from the loo package @loo in R v4.1.2. The model with the best leave-one-out cross validation score (SI Appendix 1, Table S3) is presented below (Model 1). Both the generalised linear models in Model 1 (i.e. the Bernoulli model and the Log-Normal model) were fit as multilevel models where the parameters (i.e. intercepts and slopes) were fit as correlated random effects. Using 1000 samples from the posterior distribution of Model 1 (below), we imputed the dry biomass of missing monoculture values leaving us with 1000 separate estimates of the dry biomass for each missing monoculture (see SI Appendix 4.6 for an analysis of the quality of the imputations).

#### Model 1

$$
w_i \sim \text{Bernoulli}(p_i)
$$

$$
w_i =
\begin{cases}
0 & \text{if } M_i = 0 \\
1 & \text{if } M_i > 0
\end{cases}
$$

$$
\text{logit}(p_i) = \theta_{s[i]} + \delta_{1_{s[i]}} Y_i
$$

$$
\theta_j = \bar{\theta} + \nu_1
$$

$$
\delta_{1_j} = \bar{\delta}_1 + \nu_2
$$

$$
\nu = \left( \text{diag}(\tau) \times \text{cholesky}(R) \times V^\top \right)
$$

$$
V_{k,j} \sim \text{Normal}(0, 1)
$$

$$
\bar{\theta}, \bar{\delta}_1 \sim \text{Normal}(0, 1.5)
$$

$$
\tau_\theta, \tau_\delta \sim \text{Exponential}(3)
$$

$$
R_{k,k} \sim \text{LKJcorr}(2)
$$

$$
(-M_i \mid w_i = 1) \sim \text{LogNormal}(u_i, \varepsilon)
$$

$$
u_i = \alpha_{s[i]} + \beta_{1_{s[i]}} Y_i + \beta_{2_{s[i]}} PC1_i
$$

$$
\alpha_j = \bar{\alpha} + z_1
$$

$$
\beta_{1_j} = \bar{\beta}_1 + z_2
$$

$$
\beta_{2_j} = \bar{\beta}_2 + z_3
$$

$$
z = \left( \text{diag}(\sigma) \times \text{cholesky}(L) \times Z^\top \right)
$$

$$
\varepsilon \sim \text{Exponential}(5)
$$

$$
Z_{l,j} \sim \text{Normal}(0, 1)
$$

$$
\bar{\alpha}, \bar{\beta}_1, \bar{\beta}_2 \sim \text{Normal}(0, 1)
$$

$$
\sigma_\alpha, \sigma_{\beta_1}, \sigma_{\beta_2} \sim \text{Exponential}(3)
$$

$$
L_{l,l} \sim \text{LKJcorr}(2)
$$

Using all 1000 estimates of monoculture dry biomass for the missing 298 datapoints and assuming a set of a 100 random $RYE$s drawn a from the Dirichlet distribution, we calculated the different biodiversity effects. For total complementarity and non-random overyielding, we obtained 1000 different estimates (reflecting the uncertainty in the monoculture imputations). For the net biodiversity effect, total selection, total insurance, average selection, spatial insurance, temporal insurance and spatio-temporal insurance, we obtained 100 000 different estimates reflecting the combined uncertainty in the monoculture imputations and the $RYE$s.

To obtain a pooled mean across the nine clusters for each of the biodiversity effects, we used a random-effect meta-analysis model [@koricheva2013]. For each biodiversity effect and each of the nine clusters (i), we calculated the mean and standard deviation (s) of the distribution of biodiversity effect estimates. Using the mean and standard deviation of each cluster (s), we fit an intercept-only random-effects meta-analysis model for each biodiversity effect as:

$$
\bar{x}_i \sim \text{Normal}(\theta_i, \sigma)
$$

$$
\sigma^2 = \frac{s^2}{n}
$$

$$
\theta_i \sim \text{Normal}(\mu, \tau)
$$

Where {n} is the number of samples (in this case, 1000 or 100 000), $\theta_i$ is the true mean of the $i^{th}$) function from the metafor package [@metafor] in R v4.1.2 using restricted maximum likelihood. We assessed whether the pooled mean ($\mu$), which is the model intercept in this case, differed from zero using the Knapp-Hartung method which is based on t-tests [@metafor].

Finally, we tested the hypothesis that spatial insurance effects strengthen with spatial environmental heterogeneity because responses to the environment are species-specific (or, in this case, OTU-specific). To do this, we regressed spatial environmental heterogeneity which we quantified as the multivariate dispersion of each cluster based on 14 environmental variables (SI Appendix 1, Fig. S4) with all 100 000 estimates of the spatial insurance effect of each cluster. We then examined the distribution of 100 000 slope estimates for the effect of multivariate dispersion on the spatial insurance effect. The regressions were performed using the lm() function in R v4.1.2 which uses ordinary least squares.

Unless otherwise stated, all analyses were performed in R v4.1.2. Additional packages used were dplyr [@dplyr], tidyr [@tidyr] and readr [@readr] for data handling, ggplot2 [@ggplot2], ggpubr [@ggpubr] and cowplot [@cowplot] for data visualisation, gtools [@gtools] for the Dirichlet distribution and renv [@renv] for package version management.

## Results

### *Case study 1: Rockpool macroalgae*

The net biodiversity effect in the rockpool macroalgae communities was large and positive (Mean, Highest Posterior Density Interval ($HPDI_{95\%}$): 126, $119 - 136$ % cover). This indicates that going from one to four species increases cover by more than 100% across the three time points and two places, and this effect was dominated by total complementarity (Fig. 3a). Strong total complementarity indicates that, on average, niche partitioning and/or positive interspecific interactions have a stronger effect on algal cover than intraspecific interactions. This is consistent with the mixtures having higher cover than any of the four monocultures across all times and places (SI Appendix 1, Fig. S1a, b).

Total insurance was less than a third of the net biodiversity effect (Fig. 3a, b). Total insurance was dominated by average selection (Fig. 3c), but spatial insurance was also positive (Fig. 3c). The dominance of average selection was due to *Sargassum muticum* which had, on average, two to three times more cover than the other species in monoculture (SI Appendix 1, Fig. S1a, b). Thus, even though there was positive covariance between monoculture functioning and relative abundance for three species (*Bifurcaria bifurcata*, *Fucus serratus* and *Laminaria digitata*) across space (the signature of spatial insurance, SI Appendix 1, Fig. S1c), *S. muticum* still dominated total insurance. We found no evidence for temporal or spatio-temporal insurance (Fig. 3c, SI Appendix 1, Fig. S1d).

Fig. 3: Biodiversity effects on cover (%) for the rockpool macroalgae (case study 1). (a) net biodiversity effect, total complementarity (TC) and total selection, (b) non-random overyielding (NO) and total insurance, and (c) average selection (AS), spatial insurance (SI), temporal insurance (TI) and spatio-temporal insurance (ST). Diamonds with error bars represent the mean and $95\%$ highest posterior density interval ($HPDI$). In addition, 100 random samples (unfilled circles) are also plotted. The y-axis scales differ between the three plots, but the red vertical dashed line indicates a common point at 30% for a visual reference.

### *Case study 2: Marine fouling communities*

The net biodiversity effect ranged from strong and positive (Mean, $HPDI_{95\%}$: 57.5, 50.7 -- 63.3 g) to weak and negative (Mean, $HPDI_{95\%}$: -1.03, $-2.28 - 0.093$ g) across the nine clusters. This indicates that, depending on the cluster, going from one to five OTUs could increase biomass by 57.5 g or decrease it by 1.03 g across times and places, on average. However, pooled across all clusters, the average net biodiversity effect was significantly positive (Mean, $CI_{95%}$: 24.3, $10.7 - 38$ g, SI Appendix 1, Table S2). As with the first case study, the net biodiversity effect was dominated by total complementarity, (Fig. 4a) and the mixtures frequently had higher biomass than any of the monocultures at many times and places (SI Appendix 1, Fig. S2).

Total insurance effects were strong and positive and of similar magnitude to total complementarity (Fig. 4a, b). Total insurance was dominated by average selection (Fig. 4c). This was due to the high monoculture dry biomass and dominance in mixture of the Barn OTU (*Amphibalanus improvisus*), (SI Appendix 1, Fig. S2). Spatial insurance was weaker (Fig. 4c) but still significantly positive across clusters (pooled mean, $CI_{95%}$: 1.7, $0.60 - 2.9$ g, SI Appendix 1, Table S2). We did not detect temporal nor spatio-temporal insurance effects across clusters (SI Appendix 1, Table S2).

Fig. 4: Biodiversity effects on dry biomass (g) for the marine fouling communities. (a) net biodiversity effect, total complementarity (TC) and total selection, (b) non-random overyielding (NO) and total insurance, and (c) average selection (AS), spatial insurance (SI), temporal insurance (TI) and spatio-temporal insurance (ST). Diamonds with error bars represent the pooled mean and 95% confidence interval for each effect across the nine clusters estimated using a random-effect meta-analysis model. Asterisks indicate that the pooled mean is significantly different from zero (SI Appendix 1, Table S2). For each effect and each of the nine clusters, the $95\%$ highest posterior density interval ($HPDI$, coloured lines) for the effect is shown along with 100 random samples (unfilled circles) are also plotted. The y-axis scales differ between the three plots, but the red vertical dashed line indicates a common point at 30 g for a visual reference.

Whilst spatial insurance was weak, there was variation among clusters (Fig. 4c). We hypothesised that this could be due to differences in spatial environmental heterogeneity between clusters if OTUs respond differently to spatial environmental variation. We found a positive relationship between cluster-level spatial environmental heterogeneity and the spatial insurance (Fig. 5a). The average slope $\beta$ between spatial environmental heterogeneity and the spatial insurance effect was positive across the 100 000 estimates of the spatial insurance effect ($\beta_{mean}$, $HPDI_{95\%}$: 0.56, $0.06 - 1.3$, Fig. 5b). However, this was influenced by a strong outlier (cluster H) which was the only site that had substantial presence of the Ciona OTU at some places (SI Appendix 1, Fig. S2). This led to high spatial insurance effects as the Barn OTU (*A. improvisus*) tended to dominate communities in the other clusters (SI Appendix 1, Fig. S2). Redoing the analysis without this outlier strengthened the relationship (βmean, $HPDI_{95\%}$: 0.93, $0.35 - 1.6$, SI Appendix 1, Fig. S3).

Fig. 5: Spatial insurance increases with spatial environmental heterogeneity in the marine fouling communities (a) The relationship between spatial environmental heterogeneity (quantified for each of the nine clusters using multivariate dispersion of 14 environmental variables) and spatial insurance (mean and 95% highest density posterior interval, $HPDI_{95\%}$) across the nine clusters. Light grey circles are 100 random samples from the distribution of 100 000 spatial insurance estimates for each cluster. The red lines are a sample of the 200 simple linear regression lines from a total of 100 000 regression lines (one for each of the 100 000 spatial insurance estimates). (b) Density plot of the distribution of slope estimates from the 100 000 simple linear regressions of multivariate dispersion on spatial insurance. Red circle with the error bar is the mean and 95% highest density posterior interval.

## Discussion

Our analysis of two natural marine ecosystems allowed us to quantify the complex ways in which biodiversity affects ecosystem functioning across space and time. In both systems, most of the net biodiversity effect, which was positive, was due to two effects. First, total complementarity, which quantifies local-scale species interactions. Second, average selection, which quantifies the dominance of high functioning species across space and time (*Sargassum muticum* and *Amphibalanus improvisus* in case studies 1 and 2, respectively). This suggests that, in our case studies, processes that allow local-scale species coexistence as well as the ability of high functioning species to access a wide geographic area are important for maintaining ecosystem functioning. In both ecosystems, we found evidence that variation in species' responses to the environment in space had a positive effect (i.e. positive spatial insurance). Moreover, in the marine fouling system, spatial insurance increased with spatial environmental heterogeneity. As a result, dispersal processes that allow for species sorting in space may also be an important determinant of functioning. Overall, our approach emphasises the importance of taking a multi-scale perspective in biodiversity-ecosystem functioning research.

The dominant role of total complementarity and average selection is in line with substantial experimental work showing an important role of local-scale species interactions and dominance of high functioning species [@cardinale2007a; @cardinale2011a; @gamfeldt2015a]. In comparison, the relative weakness of spatial insurance and the absence of temporal and spatio-temporal insurance may be explained by features of our case studies. First, the rockpool data come from two shores that were chosen because they had similar environmental conditions (Lars Gamfeldt, personal observation). Moreover, all three temporal measurements were taken in the same year, which is short considering the multidecadal lifespan of the focal algae species [@aberg1992]. The situation is similar in the marine fouling communities. While we aimed to maximise spatial environmental heterogeneity among the five sites within a cluster (Methods and materials), the spatial extent of the clusters was only approximately 0.25 km2, and the temporal measurements were taken over six weeks. This spatial extent is lower than previous studies from the region, which found more species turnover than we found [@berntsson2003]. The relatively similar environmental conditions across places and times of both case studies probably provided little opportunity for spatial and temporal niche partitioning.

Further evidence that the weak spatial and temporal insurance effects were due to limited environmental heterogeneity comes from (i) comparing spatial environmental heterogeneity and spatial insurance across clusters in the marine fouling communities, and (ii) comparing our results to the original application of the statistical partition [@isbell2018a]. First, there was a positive relationship between spatial environmental heterogeneity and spatial insurance in the marine fouling communities (Fig. 5). This suggests that spatial environmental heterogeneity increased spatial niche partitioning and, therefore, spatial insurance. Moreover, when removing cluster H which had relatively unique environmental conditions compared to the other clusters, the effect strengthened (SI Appendix 1, Fig. S3). Second, in the original application of the statistical partition [@isbell2018a], the authors found weak spatial insurance but strong temporal insurance. However, spatial environmental heterogeneity in their grassland experiment had only two levels (+/- nitrogen treatment), but their data spanned 18 years with a range of different weather conditions during that time (e.g. droughts, anomalously wet years). Taken together, this indicates that the magnitude of insurance effects strongly depends on the spatial and temporal scales of the data, the environmental variation that the data span [@gamfeldt2023a; @loreau2021a; @loreau2003a].

Our study indicates that insurance effects should continue to strengthen as we increase scale and, therefore, environmental heterogeneity in space and time. Broadly, this means that the biodiversity-ecosystem function field may have failed to quantify much of the positive effect of biodiversity on ecosystem functioning because most research has taken place on small scales with limited environmental heterogeneity [@qiu2020a; @gonzalez2020a]. Identifying the appropriate scale to evaluate insurance effects, however, requires insight into the focal study system. If the scale is too small, there will not be enough environmental heterogeneity to allow species to sort in time or space [@hart2017a]. This was likely the case in our rockpool experiment. On the other hand, very large scales with high environmental heterogeneity and dispersal limitation will often be associated with high turnover in the dominance of species. At these scales, concluding that insurance effects are important is, in our opinion, trivial. Moreover, it will be difficult, or even untenable, to quantify biodiversity effects because the biodiversity partition relies heavily on monoculture data (which will then not be available for many places and times). Quantifying insurance effects thus requires a match between the scale of environmental heterogeneity and the way that species respond to that heterogeneity.

In both case studies, total complementarity was strong (Figs. 3 and 4). Thus, species in mixtures, on average, had higher functioning than expected based on their functioning in monoculture. In particular, functioning in mixture was higher than even the highest functioning monocultures at many times and places (SI Appendix 1, Figs. S1 and S2). There are at least three non-mutually exclusive causes for this. First, our case studies took place in natural environments which may have higher local-scale environmental heterogeneity than many experimental systems that often occur in highly controlled conditions. Second, monocultures were created by removing species whilst mixtures were undisturbed. This could have inflated the mixture functioning relative to the monoculture functioning. We did not directly include controls for biomass removal [@stachowicz2008; @bracken2017a] but mitigated this problem by initially removing all algal biomass in the intertidal rockpool macroalgae study and by scaling monoculture biomass by area covered in the fouling community study (SI Appendix 4.4, Fig. S13). Finally, there may simply be strong niche partitioning between species in our two systems. Indeed, in an experiment with fouling communities on the east coast of the USA, over time, species-rich communities occupied the available space on the experimental panels to a considerably higher degree compared to communities with only individual species [@stachowicz1999a]. Species-rich panels had higher cover because different species peaked in cover during different time periods of the experiment [@stachowicz2008]. Our data, however, do not allow us to mechanistically explain the strong total complementarity that we observed.

The approach we used to incorporate uncertainty in relative expected yields worked well on simulated data (SI Appendix 3, Fig. S11) and, in case study 2, we were able to obtain relatively accurate monoculture imputations (SI Appendix 4.6, Fig. S17 and S18). We are thus confident that we were able to estimate all biodiversity insurance effects, and their relative magnitude, with high accuracy for both case studies. Our methods provide a promising methodological pipeline for future studies, allowing researchers to work with incomplete data from natural systems to estimate biodiversity effects at multiple scales of space and time.

The most challenging part of applying our approach to incomplete data from natural systems is obtaining sufficient monoculture data. Some ecological systems are not as amenable to manipulation as our systems were, which means it may not be possible to even obtain patchy monoculture data. One option to estimate monoculture functioning when no direct monoculture data are available is to use more advanced statistical approaches such as the Joint Species Distribution Modelling framework [@ovaskainen2017] or the Diversity-Interactions Modelling framework [@connolly2013]. These methods simultaneously model all species and their interactions and as a result can, in principle, generate monoculture functioning predictions based purely on mixture data (as suggested by [@isbell2018b]). The problem is that statistical approaches based only on mixture data will inevitably predict beyond the range of the data. However, with mixture data that covers a wide range of species compositions (e.g. many two-species mixtures), it may be feasible. Another option is to field-parameterise population models as is common in studies of species coexistence [@levine2009]. If they are set up so that modelled abundances correspond to or can be easily converted to the ecosystem function of interest, these models can be used to generate monoculture predictions by setting interspecific competition to zero in the parameterised model. Generally, these types of models are difficult to parameterise, but recent advances using functional traits and species abundance data may facilitate this in the future [@chalmandrier2021; @chalmandrier2022]. These (or other) statistical or theory-driven approaches may be the only options if researchers want to calculate these biodiversity effects in systems where monocultures cannot be artificially created.

### Conclusions

By developing a methodological pipeline built around a rigorously derived statistical partition [@isbell2018c], we were able to dissect the various ways in which biodiversity can affect ecosystem functioning in two natural marine ecosystems at large spatial and temporal. This not only showed that biodiversity effects at large scales were strong and positive but also provided insights into the mechanisms responsible for these positive effects, namely: local-scale species interactions, local-scale dominance by high functioning species, and spatial niche partitioning all contributed to the positive effect that biodiversity had on ecosystem functioning. If, like in many previous studies [@thompson2018a; @thompson2021a; @chisholm2013a], we would have only analysed the slope of the relationship between biodiversity and functioning, all we could have concluded is that the slope does, or does not, vary with scale, which yields little insight. Overall, our results suggest that if we want to fully understand how biodiversity affects the functioning of ecosystems at a range of spatial and temporal scales, we must move beyond simply correlating biodiversity with measures of ecosystem functioning. Our pipeline provides a way of doing that.

## Acknowledgements

We would like to thank Per Jonsson and Jon Havenhand for help with the experimental design and for reviewing initial drafts of the manuscript. Per Bergström is thanked for providing access to the GIS data. We would like to thank Mael Grosse for help with species identification and photography for case study 2. Finally, a special thanks to John Griffin, Adam Bates, Matthew McHugh, Patricia Masterson, and volunteers at the Marine Biological Association of the UK in Plymouth for help with case study 1, and Julia Murata, Elena Schrofner-Brunner, Lara Martins, Pedro Victorino de Almeida Dubois de La Patellière and Jesper Hassellöv for help collecting the data for case study 2. The project was supported by a doctoral studentship from the University of Gothenburg awarded to James Hagan and a research grant 2020-03521 from the Swedish Research Council VR awarded to Lars Gamfeldt.

## Author contributions

JH conceived the idea with input from BSB and LG. JH, BSB and LG designed the experiments. LG led the data collection for case study 1, and BSB led the data collection for case study 2. JH analysed the data with input from BSB. JH wrote the first draft with input from BSB and LG. All authors helped revise the manuscript.

## Conflict of interest statement

We declare no conflicts of interest.
