---
title: "Quantifying biodiversity effects across times and places"
output: html_notebook
---

# Bioversity-functioning partitions

## Relative yield

What is overyielding? Overyielding occurs when the production of a species in mixture exceeds the expected production of that species based on its monoculture production. This indicates that, for some reason, mixtures of species are greater than the sum of their parts (i.e. their monocultures). Therefore, we often want to quantify overyielding behaviour to determine if there are benefits to mixing multiple species together.

This brings us to *relative yield*. Relative yield does not measure overyielding directly. Rather, we use relative yield as a tool to quantify overyielding. Specifically, we quantify relative yield as the mixture yield of species i divided by the monoculture yield of species i. Thus, for the observed relative yield, we quantify it as:

* RYobs,i = Yobs,i/Mi 

Where **RYobs,i** is the relative yield of species i, **Yobs,i** is the observed yield in mixture of species i and **Mi** is the monoculture yield of species i.

If we want to know whether there is overyielding, we have to compare the observed relative yield to something. If our mixture is sown with equal proportions of two species, then the *expected yield* of species i (Yexp,i) would be half the monoculture value of species i. Therefore, the expected relative yield of species (RYexp,i) would be 0.5. This is because the expected yield of species i is half its monoculture. This can be seen mathematically as:

* RYexp,i = 0.5 = Yexp,i/Mi
* Yexp,i = 0.5*Mi

In this case, if the observed relative yield (RYobs,i) exceeds the expected relative yield (RYexp,i) then species i in mixture has a higher yield than expected based on the monoculture yield (Mi) and the sown proportions (i.e. intial proportion). In experimental data, we simply use the sown proportion as our RYe. In natural systems, we will have to be a bit more clever. Probably, we will either have to assume a distribution of possible initial proportions (i.e. drawing from the Dirichlet distribution) or use multiple time-points.

The relative yield calculations are the bread and butter of the original Loreau and Hector (2001) partition and Isbell et al.'s (2018) extension. Specifically, we measure the net biodiversity effect NBE:

* sum( delta RYi * Mi)

Where delta RYi is the difference between RYobs,i and RYexp,i for species i. This NBE is then partitioned into two different terms in Loreau and Hector's (2001) partition, the complementarity effect (CE) and the selection effect (SE):

* CE = N mean( delta RYi ) mean( Mi ) 
* SE = N cov( delta RYi, Mi )

The selection effect occurs when species with higher than average monoculture yields also have higher relative yields than expected. Complementarity effects occur when species yields are on average higher than expected based on their monoculture yields.


## Isbell et al.'s (2018) biodiversity effects

1. Non-random overyielding

The non-random overyielding term is quite confusing because it's not exactly clear what the delta RYobs,ijk term measures. The explanation in the text says that it is the extent to which the most productive species in monoculture tend to overyield most in mixtures. They then say that overyielding is quantified relative to observed rather than initial relative abundance... The formula is:

* PTN cov( delta RYobs,ijk, Mijk)

My initial explanation is that if there is a high RYobs,ijk but the species is dominating in the mixture (i.e. high Pobs,ijk), then this is not non-random overyielding because we it is not overyielding necessarily more than we expect based on its proportion?

```{r}



```

